#!/bin/bash

LOCAL_SETTINGS_FILE=$(source ${CONTAINER_SCRIPTS_ROOT}/setup/setup.sh ${BASH_SOURCE} ${LOCAL_SETTINGS_FILE})

source ${CONTAINER_SCRIPTS_ROOT}/setup/utils/get_tag.sh

# ELASTIC_CONT_NAME
ELASTIC_CONT_NAME="elastic_cont"

echo "ELASTIC_CONT_NAME=${ELASTIC_CONT_NAME}" >> ${LOCAL_SETTINGS_FILE}

# ELASTIC_IMAGE
ELASTIC_IMAGE=$(get_tag $BASH_SOURCE)

echo "ELASTIC_IMAGE=${ELASTIC_IMAGE}" >> ${LOCAL_SETTINGS_FILE}