FROM docker.io/library/mariadb:10.5
RUN apt-get update && apt-get upgrade -y
RUN rm -rf /var/lib/apt/lists/*
COPY ./maria.sh /docker-entrypoint-initdb.d/maria.sh
RUN touch /tmp/.finished
RUN chmod 0666 /tmp/.finished
RUN chown mysql:mysql /tmp/.finished
RUN chown mysql:mysql /docker-entrypoint-initdb.d/maria.sh
RUN chmod 0555 /docker-entrypoint-initdb.d/maria.sh
#RUN chown root:root /var/lib/mysql