#!/bin/bash

LOCAL_SETTINGS_FILE=$(source ${CONTAINER_SCRIPTS_ROOT}/setup/setup.sh ${BASH_SOURCE} ${LOCAL_SETTINGS_FILE})

# REDIS_CONT_NAME

REDIS_CONT_NAME="redis_cont"

echo "REDIS_CONT_NAME=${REDIS_CONT_NAME}" >> ${LOCAL_SETTINGS_FILE}

# REDIS_IMAGE
REDIS_IMAGE=$(get_tag)

echo "REDIS_IMAGE=${REDIS_CONT_NAME}" >> ${LOCAL_SETTINGS_FILE}