FROM docker.io/library/mariadb
RUN apt-get update && apt-get upgrade -y
RUN rm -rf /var/lib/apt/lists/*
COPY ./maria.sh /docker-entrypoint-initdb.d/maria.sh
RUN chmod +x /docker-entrypoint-initdb.d/maria.sh
#RUN chown mysql:mysql /docker-entrypoint-initdb.d/maria.sh
#RUN chown root:root /var/lib/mysql