# build command is: podman build --tag='python:django' -f='dockerfile_django'
FROM docker.io/library/python
ARG PROJECT_NAME=${PROJECT_NAME}
ENV DJANGO_SETTINGS_MODULE=settings
ENV PYTHONPATH="/etc/opt/${PROJECT_NAME}/settings/:/opt/${PROJECT_NAME}/"
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y supervisor libmagic1 libmagickwand-dev libjpeg62-turbo-dev zlib1g-dev python3-pil python3-pil.imagetk python-wheel
RUN rm -rf /var/lib/apt/lists/*
RUN mkdir -p /opt/${PROJECT_NAME}; 
RUN mkdir -p /var/log/${PROJECT_NAME}; 
RUN mkdir -p /etc/opt/${PROJECT_NAME}/settings; 
RUN mkdir -p /etc/opt/${PROJECT_NAME}/static_files;
RUN useradd -m artisan
RUN python -m venv /home/artisan/django_env
RUN cd /home/artisan/django_env & source ./bin/activate
COPY ./pip_requirements_prod /tmp/pip_requirements
RUN python -m pip install --upgrade pip && pip install --no-cache-dir -r /tmp/pip_requirements
RUN rm -r /tmp/pip_requirements
COPY ${CODE_PATH}/media /etc/opt/${PROJECT_NAME}/static_files/media
COPY ${SCRIPTS_ROOT}/settings/supervisor_gunicorn /etc/supervisor/conf.d/gunicorn_supervisord.conf
