# build command is: podman build --tag='python:django' -f='dockerfile_django'
FROM docker.io/linuxserver/swag
ARG SCRIPTS_ROOT=${SCRIPTS_ROOT}
RUN rm -rf /var/run/s6/etc/services.d/php-fpm
COPY ${SCRIPTS_ROOT}/swag/default /config/nginx/site-confs/default
COPY ${SCRIPTS_ROOT}/swag/nginx /config/nginx/nginx.conf
RUN chown abc:users /config/nginx/nginx.conf
RUN chown abc:users /config/nginx/site-confs/default
RUN mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old
RUN ln -s /config/nginx/nginx.conf /etc/nginx/nginx.conf