FROM docker.io/linuxserver/swag
RUN rm -rf /var/run/s6/etc/services.d/php-fpm
COPY ./swag/default /config/nginx/site-confs/default
COPY ./swag/nginx /config/nginx/nginx.conf
RUN chown abc:users /config/nginx/nginx.conf
RUN chown abc:users /config/nginx/site-confs/default
RUN mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old
RUN ln -s /config/nginx/nginx.conf /etc/nginx/nginx.conf