# build command is: podman build --tag='python:django' -f='dockerfile_django'
FROM docker.io/library/python
ARG PROJECT_NAME=${PROJECT_NAME}
ENV PROJECT_NAME=${PROJECT_NAME}
ENV DJANGO_SETTINGS_MODULE=settings
ENV PYTHONPATH="/etc/opt/${PROJECT_NAME}/settings/:/opt/${PROJECT_NAME}/"
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y libmagic1 libmagickwand-dev libjpeg62-turbo-dev zlib1g-dev python3-pil python3-pil.imagetk
RUN rm -rf /var/lib/apt/lists/*
RUN mkdir -p /opt/${PROJECT_NAME} /var/log/${PROJECT_NAME} /etc/opt/${PROJECT_NAME}/settings /etc/opt/${PROJECT_NAME}/static_files/ /etc/opt/${PROJECT_NAME}/media_files/media /etc/opt/${PROJECT_NAME}/media_files/media/cache /etc/opt/${PROJECT_NAME}/media_files/media/uploads
RUN chmod 0770 -R /etc/opt/${PROJECT_NAME}/media_files
RUN useradd -m artisan
RUN chown artisan:artisan /opt/${PROJECT_NAME} /var/log/${PROJECT_NAME} /etc/opt/${PROJECT_NAME}/settings /etc/opt/${PROJECT_NAME}/static_files
RUN chown artisan:artisan -R /etc/opt/${PROJECT_NAME}/media_files
RUN mkdir /home/artisan/django_venv
RUN chown artisan:artisan /home/artisan/django_venv
ENV VIRTUAL_ENV=/home/artisan/django_venv
RUN su artisan -c "python3 -m venv $VIRTUAL_ENV"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
COPY ./pip_requirements_prod /tmp/pip_requirements
RUN su artisan -c "python -m pip install --upgrade pip wheel" && su artisan -c "pip install --no-cache-dir --use-deprecated=legacy-resolver -r /tmp/pip_requirements"
RUN rm -r /tmp/pip_requirements
COPY ./django/media/* /etc/opt/${PROJECT_NAME}/media_files/media
RUN touch /tmp/manage_output && chmod 0666 /tmp/manage_output
COPY ./django/init /init
RUN chmod +x /init
CMD /init