#!/bin/bash

mysql -u'root' -p'davebob' -h'localhost' --protocol='tcp' -e "CREATE DATABASE ${DB_NAME} CHARSET utf8; grant all privileges on ${DB_NAME}.* TO ${DB_USER}@${DB_HOST} identified by '${DB_PASSWORD}'; Delete from mysql.user where host='%';"