#!/bin/bash

LOCAL_SETTINGS_FILE=$(source ${CONTAINER_SCRIPTS_ROOT}/setup/setup.sh ${BASH_SOURCE} ${LOCAL_SETTINGS_FILE})

source ${CONTAINER_SCRIPTS_ROOT}/setup/utils/get_tag.sh

# DUCKDNS_DOMAIN
read -p "Duckdns domain : [ ${SITE_ADDRESS} ]" DUCKDNS_DOMAIN
DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN:${SITE_ADDRESS}}

echo "DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN}" >> ${LOCAL_SETTINGS_FILE}

# DUCKDNS_CONT_NAME
DUCKDNS_CONT_NAME="duckdns_cont"

echo "DUCKDNS_CONT=${DUCKDNS_CONT}" >> ${LOCAL_SETTINGS_FILE}

# DUCKDNS_IMAGE
DUCKDNS_IMAGE=$(get_tag $BASH_SOURCE)

echo "DUCKDNS_IMAGE=${DUCKDNS_IMAGE}" >> ${LOCAL_SETTINGS_FILE}