#!/bin/bash
source ${CONTAINER_SCRIPTS_ROOT}/setup/utils/local_settings.sh ${BASH_SOURCE}

LOCAL_SETTINGS_FILE=$(local_settings ${LOCAL_SETTINGS_FILE})

source ${CONTAINER_SCRIPTS_ROOT}/setup/setup.sh

# DUCKDNS_DOMAIN
read -p "Duckdns domain : [ ${SITE_ADDRESS} ]" DUCKDNS_DOMAIN
DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN:${SITE_ADDRESS}}

echo "DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN}" >> ${LOCAL_SETTINGS_FILE}

