#!/bin/bash

source ${CONTAINER_SCRIPTS_ROOT}/setup/setup.sh

# DUCKDNS_DOMAIN
read -p "Duckdns domain : [ ${SITE_ADDRESS} ]" DUCKDNS_DOMAIN
DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN:${SITE_ADDRESS}}

echo "DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN}" >> ${LOCAL_SETTINGS_FILE}

