#!/bin/bash
#
# chkconfig: 35 90 12
# description: gunicorn server start
#

# Get function from functions library
. /etc/init.d/functions

# Start the service FOO
start() {
        initlog -c "echo -n Starting FOO server: "
        /usr/local/bin/gunicorn -c /etc/opt/${project_name}/settings/gunicorn.conf.py ${django_project_name}.wsgi:application &
        ### Create the lock file ###
        touch /var/lock/subsys/gunicorn
        success $"gunicorn server startup"
        echo
}

# Restart the service FOO
stop() {
        initlog -c "echo -n Stopping gunicorn server: "
        killproc gunicorn
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/gunicorn
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status gunicorn
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
