# build command is: podman build --tag='python:django' -f='dockerfile_django'
FROM docker.io/library/python
ARG DJANGO_PROJECT_NAME=${PROJECT_NAME}
ENV DJANGO_PROJECT_NAME=${DJANGO_PROJECT_NAME}
ENV DJANGO_CODE_PATH=${DJANGO_CODE_PATH}
ENV DJANGO_SETTINGS_MODULE=settings
ENV PYTHONPATH=/etc/opt/${DJANGO_PROJECT_NAME}/settings/:/opt/${DJANGO_PROJECT_NAME}/
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y libmagic1 libmagickwand-dev libjpeg62-turbo-dev zlib1g-dev python3-pil python3-pil.imagetk
RUN rm -rf /var/lib/apt/lists/*
COPY ./pip_requirements /tmp/pip_requirements
RUN python -m pip install --upgrade pip && pip install --no-cache-dir -r /tmp/pip_requirements
RUN rm -r /tmp/pip_requirements
RUN mkdir -p /opt/${DJANGO_PROJECT_NAME}
RUN mkdir -p /var/log/${DJANGO_PROJECT_NAME}
RUN mkdir -p /etc/opt/${DJANGO_PROJECT_NAME}/settings
RUN mkdir -p /etc/opt/${DJANGO_PROJECT_NAME}/static_files
