#!/bin/bash 

sed -i "s/SECRET_KEY=.*/SECRET_KEY=\'$(sed -e 's/[&\\/]/\\&/g; s/$/\\/' -e 's/\\$//' <<< $(tr -dc 'a-z0-9!@#$%^&*(-_=+)' < /dev/urandom | head -c50))\'/" /etc/opt/${PROJECT_NAME}/settings/.env