#!/bin/bash
###
## This file is renamed .env and is copied in to scripts folder
## There will be no variable substitution, so please complete it 
## thoroughly.  Bash variables like $HOME are for illustrative
## purposes only.
###

## SHARED  PROJECT_NAME is set in create_all.sh
HOST_LOG_DIR=              # $HOME/${PROJECT_NAME}/logs/   ie /home/user_name/logs

## POD SETTINGS
POD_NAME=                           # name of the pod
PORT1_DESCRIPTION=0.0.0.0:443:443
PORT2_DESCRIPTION=0.0.0.0:80:80

## DJANGO
DJANGO_PROJECT_NAME=${PROJECT_NAME}
DJANGO_CONT_NAME=django_cont
DJANGO_IMAGE=python:django
DJANGO_LOG_DIR=/var/log/django/

## CLAMAV
CLAM_CONT_NAME=clamav_cont
CLAM_IMAGE=docker.io/mkodockx/docker-clamav

## DUCKDNS/SWAG
DUCKDNS_CONT_NAME=duckdns_cont
DUCKDNS_SUBDOMAIN=                        # ie ceramicisles.duckdns.org
DUCKDNS_IMAGE=docker.io/linuxserver/duckdns
DUCKDNS_TOKEN=                            # your duckdns token

## MEMCACHED
MEMCACHED_CONT_NAME=memcached_cont
MEMCACHED_IMAGE=docker.io/library/memcached

## ELASTIC SEARCH
ELASTIC_CONT_NAME=elastic_cont
ELASTIC_IMAGE=docker.io/library/elasticsearch

## MARIADB
MARIA_CONT_NAME=mariadb_cont
MARIA_IMAGE=docker.io/library/mariadb
DB_NAME=                                 # database name for django
DB_USER=                                 # django db user
DB_PASSWORD=                             # django db password

## SWAG
SWAG_CONT_NAME=swag_cont
SWAG_IMAGE=docker.io/linuxserver/swag
EXTRA_DOMAINS=ceramicisles.org        # in my case I have a TLD redirecting to my duckdns domain this 'EXTRA_DOMAINS' entry is supposed to help swag generate a certificate that covers the TLD also.
SWAG_HOST_VOL_STATIC=                  # ie /etc/opt/${PROJECT_NAME}/static_files/
SWAG_CONT_VOL_STATIC=/opt/static_files/
SWAG_CONT_LOG_DIR=/config/logs/
