#!/bin/bash
###
## This file is renamed .env and is copied in to scripts folder
## There will be no variable substitution, so please complete it 
## thoroughly.  Bash variables like $HOME are for illustrative
## purposes only.
###

## SHARED
PROJECT_NAME=${project_name}
HOST_LOG_DIR=${host_log_dir}

## POD SETTINGS
POD_NAME=${pod_name}
PORT1_DESCRIPTION=0.0.0.0:443:443
PORT2_DESCRIPTION=0.0.0.0:80:80

## DJANGO
DJANGO_CONT_NAME=django_cont
DJANGO_IMAGE=python:django
DJANGO_CONT_LOG_DIR=/var/log/${PROJECT_NAME}/
DJANGO_HOST_STATIC_VOL=${host_static_dir}
DJANGO_CONT_STATIC_VOL=/etc/opt/${PROJECT_NAME}/static_files

## CLAMAV
CLAM_CONT_NAME=clamav_cont
CLAM_IMAGE=docker.io/mkodockx/docker-clamav:latest

## DUCKDNS/SWAG
DUCKDNS_CONT_NAME=duckdns_cont
DUCKDNS_SUBDOMAIN=${duckdns_domain}
DUCKDNS_IMAGE=docker.io/linuxserver/duckdns:latest
DUCKDNS_TOKEN=${duckdns_token}

## MEMCACHED
MEMCACHED_CONT_NAME=memcached_cont
MEMCACHED_IMAGE=docker.io/library/memcached:1.6.9

## ELASTIC SEARCH
ELASTIC_CONT_NAME=elastic_cont
ELASTIC_IMAGE=docker.io/library/elasticsearch:7.11.2

## MARIADB
MARIA_CONT_NAME=mariadb_cont
MARIA_IMAGE=docker.io/library/mariadb:10.5.9
DB_NAME=${db_name}
DB_USER=${db_user}
DB_PASSWORD=${db_password}
DB_HOST=${db_host}

## SWAG
SWAG_CONT_NAME=swag_cont
SWAG_IMAGE=docker.io/linuxserver/swag:version-1.14.0
EXTRA_DOMAINS=${tld_domain}
SWAG_HOST_VOL_STATIC=${host_static_dir}
SWAG_HOST_LOG_DIR=${swag_host_log_dir}
SWAG_CONT_VOL_STATIC=/opt/static_files/
SWAG_CONT_LOG_DIR=/config/log/
