#!/bin/bash
###
## This file is renamed .env and is placed in the settings folder where django's settings.py resides
## There is no variable substitution so any bash $variables are for illustrative purposes only.
###
PROJECT_NAME=                                     # this is asked for several times also during scripts running
BASE_DIR=                                         # this is the dir where the django_artisan code resides, ie /opt/${PROJECT_NAME}
SECRET_KEY=                                       # DJANGO secret key
ALLOWED_HOSTS1=127.0.0.1                          # localhost 
ALLOWED_HOSTS2=                                   # yoursubdomain.duckdns.org
ALLOWED_HOSTS3=                                   # your top level domain, if you have one
DB_ENGINE=django.db.backends.mysql
DB_NAME=                                          # django db name
DB_USER=                                          # django db user
DB_PASSWORD=                                      # django db password
DB_HOST=127.0.0.1                                 # because containers are in a pod, localhost is used to communicate
DB_PORT=3306
MEMCACHED_ADDRESS=127.0.0.1:11211
STATIC_BASE_ROOT=                                 # this is the directory that contains links to the static and media files ie /etc/opt/${PROJECT_NAME}/static_files/
EMAIL_APP_ADDRESS=                                #most likely something@gmail.com
EMAIL_APP_KEY=                                    #gmail app password https://support.google.com/accounts/answer/185833?hl=en
DUCKDNS_FQ_DOMAIN=                                # yoursubdomain.duckdns.org
CUSTOM_SALT=                                      # a custom salt value for email token generation
RECAPTCH_PUBLIC_KEY=                              # google recaptcha pub key  https://developers.google.com/recaptcha/intro
RECAPTCHA_PRIVATE_KEY=                            # google recaptcha priv key
CLAMAV_ADDRESS=tcp://127.0.0.1:3310
ELASTIC_SEARCH_ADDRESS=localhost:9200
SITE_NAME=                                        # as used on header of web page eg "Ceramic Isles"
